#!/bin/env bash
# this will be the shell used by fzf to run commands
SHELL="$(command -v bash)"

if command -v fzf > /dev/null 2>&1; then
  FUZZYSEL=fzf
  HEADER="[ENTER] Add/Remove selected [TAB] Toggle selection [ALT-F] File list [ALT-H] Homepage"
  export FZF_DEFAULT_OPTS="--inline-info --marker=M"
elif command -f sk > /dev/null 2>&1; then
  FUZZYSEL=sk
  HEADER="[ENTER] Add/Remove selected [TAB] Toggle selection"
  export SKIM_DEFAULT_OPTIONS="--inline-info"
else
  echo "Unable to find fuzzy selector [fzf, sk]"
  exit
fi

#shellcheck disable=SC2016
selected="$(
  xbps-query -R --search= \
    | sed -Er "s/(\[\*\].*)/$( printf "\033[0;32m" )\1$( printf "\033[0m" )/"\
      | "${FUZZYSEL}" \
        --header="${HEADER}" \
        --prompt "Package name > " \
        --layout=reverse-list \
        --cycle \
        --preview="xq {2}" \
        --preview-window=down:wrap \
        --ansi -e -m \
        --border=sharp \
        --no-sort \
        --bind 'alt-f:preview:xbps-query -v -R -f {2}' \
        --bind 'alt-h:execute-silent[nohup xdg-open "$(xbps-query -p homepage -R {2})" &]' \
        ${1:+--query "$1"}
)"

[ -z "${selected}" ] && exit

while read -r line; do
  if echo "${line}" | grep -q "\[\*\]" >/dev/null 2>&1; then
    UNINSTALL+=( "$( echo "${line}" | awk '{ print $2 }' )" )
  else
    INSTALL+=( "$( echo "${line}" | awk '{ print $2 }' )" )
  fi
done <<<"${selected}"

if [ "$(id -u)" -eq 0 ]; then
  if [ -n "${UNINSTALL[*]}" ]; then
    echo "Executing xbps-remove -R " "${UNINSTALL[@]}"
    xbps-remove -R "${UNINSTALL[@]}"
  fi
  if [ -n "${INSTALL[*]}" ]; then
    echo "Executing xbps-install -S" "${INSTALL[@]}"
    xbps-install -S "${INSTALL[@]}"
  fi
else
  echo "Run fuzzypkg as root to add or remove packages"
fi
